import { createAdminClient } from '@/lib/supabase-server'
import type { Category } from '@/types'
import { buildArticleDraft, generateKeywordIdeas } from './content'
import { generateSerpApiKeywordIdeas } from './serpapi'
import { cleanupExternalLinks } from '@/lib/normalize-links'

function ensureCategory(category: string | null | undefined): Category {
  const allowed: Category[] = [
    'Investing',
    'Personal Finance',
    'Credit',
    'Taxes',
    'Real Estate',
    'Retirement',
  ]

  return allowed.includes(category as Category)
    ? (category as Category)
    : 'Personal Finance'
}

function cleanKeyword(value: any) {
  return String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

export async function insertKeywordIdeas(input?: any) {
  const supabase = createAdminClient()
  const requested = Math.min(50, Math.max(1, Number(input?.howMany ?? 20) || 20))
  const candidateCount = Math.min(50, requested * 3)

  const serpApiIdeas = await generateSerpApiKeywordIdeas({ ...input, howMany: candidateCount })
  const rawIdeas = serpApiIdeas.length > 0
    ? serpApiIdeas
    : generateKeywordIdeas({ ...input, howMany: candidateCount })

  const ideas = rawIdeas.map((idea) => ({
    keyword: cleanKeyword(idea.keyword),
    category: ensureCategory(idea.category),
    intent: idea.intent || 'informational',
    priority: Number(idea.priority ?? 100),
    source: idea.brief?.source === 'serpapi' ? 'serpapi' : 'automation',
    status: 'queued',
    brief: idea.brief || {},
    notes: idea.brief?.source === 'serpapi' ? 'Generated by CashClimb SerpAPI automation.' : 'Generated by CashClimb automation.',
  }))

  const inserted: any[] = []
  const skipped: any[] = []

  for (const idea of ideas) {
    if (inserted.length >= requested) break
    if (!idea.keyword) continue

    const { data: existing } = await supabase
      .from('keyword_queue')
      .select('id')
      .eq('keyword', idea.keyword)
      .eq('category', idea.category)
      .in('status', ['queued', 'processing', 'completed'])
      .maybeSingle()

    if (existing) {
      skipped.push({ keyword: idea.keyword, reason: 'already exists' })
      continue
    }

    const { data, error } = await supabase
      .from('keyword_queue')
      .insert(idea)
      .select('*')
      .single()

    if (error) {
      skipped.push({ keyword: idea.keyword, reason: error.message })
      continue
    }

    if (data) inserted.push(data)
  }

  return {
    inserted: inserted.length,
    skipped: skipped.length,
    keywords: inserted,
    skippedKeywords: skipped,
  }
}

async function getNextQueuedKeyword(keywordId?: string | null) {
  const supabase = createAdminClient()

  if (keywordId) {
    const { data, error } = await supabase
      .from('keyword_queue')
      .select('*')
      .eq('id', keywordId)
      .eq('status', 'queued')
      .maybeSingle()

    if (error) throw error
    return data
  }

  const { data, error } = await supabase
    .from('keyword_queue')
    .select('*')
    .eq('status', 'queued')
    .order('created_at', { ascending: true })
    .limit(1)
    .maybeSingle()

  if (error) throw error
  return data
}

async function lockKeyword(keyword: any) {
  const supabase = createAdminClient()

  const { data, error } = await supabase
    .from('keyword_queue')
    .update({
      status: 'processing',
      notes: 'Draft generation started.',
    })
    .eq('id', keyword.id)
    .eq('status', 'queued')
    .select('*')
    .maybeSingle()

  if (error) throw error
  return data
}

async function markKeywordCompleted(keywordId: string) {
  const supabase = createAdminClient()

  await supabase
    .from('keyword_queue')
    .update({
      status: 'completed',
      processed_at: new Date().toISOString(),
      notes: 'Draft generated successfully.',
    })
    .eq('id', keywordId)
}

async function markKeywordFailed(keywordId: string, message: string) {
  const supabase = createAdminClient()

  await supabase
    .from('keyword_queue')
    .update({
      status: 'failed',
      notes: message || 'Draft generation failed.',
    })
    .eq('id', keywordId)
}

async function completeDuplicateKeywords(keyword: string, category: Category) {
  const supabase = createAdminClient()

  await supabase
    .from('keyword_queue')
    .update({
      status: 'completed',
      processed_at: new Date().toISOString(),
      notes: 'Skipped because a draft already exists for this keyword.',
    })
    .eq('keyword', keyword)
    .eq('category', category)
    .in('status', ['queued', 'processing', 'failed'])
}

async function existingPostForKeyword(keyword: string) {
  const supabase = createAdminClient()

  const { data } = await supabase
    .from('posts')
    .select('id,title,slug')
    .eq('primary_keyword', keyword)
    .maybeSingle()

  return data || null
}

export async function createDraftFromKeyword(keywordId?: string | null): Promise<any> {
  const supabase = createAdminClient()

  const keyword = await getNextQueuedKeyword(keywordId)

  if (!keyword) {
    return {
      skipped: true,
      reason: keywordId ? 'Keyword not found or not queued.' : 'No queued keywords found.',
    }
  }

  const lockedKeyword = await lockKeyword(keyword)

  if (!lockedKeyword) {
    return {
      skipped: true,
      reason: 'Keyword already taken by another run.',
      keywordId: keyword.id,
    }
  }

  const normalizedKeyword = cleanKeyword(lockedKeyword.keyword)
  const category = ensureCategory(lockedKeyword.category)

  try {
    const existingPost = await existingPostForKeyword(normalizedKeyword)

    if (existingPost) {
      await completeDuplicateKeywords(normalizedKeyword, category)

      return {
        skipped: true,
        reason: 'Draft already exists for this keyword.',
        keyword: normalizedKeyword,
        post: existingPost,
      }
    }

    const draft = buildArticleDraft({
      keyword: normalizedKeyword,
      category,
      intent: lockedKeyword.intent,
      brief: lockedKeyword.brief,
    })

    const uniqueSlug = await nextAvailableSlug(draft.slug)
    const cleanedBody = await cleanupExternalLinks(draft.body, {
      validateExternal: true,
      removeInvalid: true,
    })

    const { data: post, error: postError } = await supabase
      .from('posts')
      .insert({
        title: draft.title,
        slug: uniqueSlug,
        excerpt: draft.excerpt,
        body: cleanedBody,
        category: draft.category,
        author: draft.author,
        cover_url: null,
        published: false,
        read_time: draft.read_time,
        primary_keyword: draft.primary_keyword,
        related_keywords: draft.related_keywords,
        seo_title: draft.seo_title,
        seo_description: draft.seo_description,
        status: draft.status,
        quality_score: draft.quality_score,
        risk_level: draft.risk_level,
        review_notes: draft.review_notes,
        workflow_meta: {
          ...(draft.workflow_meta || {}),
          keywordQueueId: lockedKeyword.id,
          generatedBy: 'automation_batch',
        },
      })
      .select('*')
      .single()

    if (postError) throw postError

    await supabase.from('quality_checks').insert({
      post_id: post.id,
      score: draft.evaluation.score,
      passed: draft.evaluation.passed,
      risk_level: draft.evaluation.risk_level,
      checks: draft.evaluation.checks,
    })

    await supabase.from('generation_runs').insert({
      post_id: post.id,
      keyword_queue_id: lockedKeyword.id,
      step: 'draft_generation',
      model: 'cashclimb-template-engine',
      status: 'completed',
      details: {
        keyword: normalizedKeyword,
        qualityScore: draft.evaluation.score,
        slug: uniqueSlug,
      },
    })

    await markKeywordCompleted(lockedKeyword.id)

    return {
      created: true,
      keyword: normalizedKeyword,
      keywordId: lockedKeyword.id,
      post,
      evaluation: draft.evaluation,
    }
  } catch (error: any) {
    const message = error?.message || 'Draft generation failed.'

    await markKeywordFailed(lockedKeyword.id, message)

    await supabase.from('generation_runs').insert({
      keyword_queue_id: lockedKeyword.id,
      step: 'draft_generation',
      model: 'cashclimb-template-engine',
      status: 'failed',
      error_message: message,
      details: {
        keyword: normalizedKeyword,
      },
    })

    throw error
  }
}


async function queuedKeywordCount() {
  const supabase = createAdminClient()
  const { count, error } = await supabase
    .from('keyword_queue')
    .select('id', { count: 'exact', head: true })
    .eq('status', 'queued')
  if (error) throw error
  return count || 0
}

export async function runAutomationBatch(options?: {
  keywordCount?: number
  draftCount?: number
  focus?: string
}) {
  const keywordCount = Math.max(1, Math.min(50, Number(options?.keywordCount ?? 10) || 10))
  const draftCount = Math.max(1, Math.min(10, Number(options?.draftCount ?? 1) || 1))

  let keywords: any = {
    inserted: 0,
    skipped: 0,
    keywords: [],
    skippedKeywords: [],
  }

  // Queue-first behavior: use existing queued keywords before generating new ideas.
  const queuedBefore = await queuedKeywordCount()
  if (queuedBefore < draftCount) {
    keywords = await insertKeywordIdeas({
      howMany: keywordCount,
      focus: options?.focus ?? 'Mixed',
    })
  }

  const drafts: any[] = []
  let attempts = 0
  const maxAttempts = Math.max(5, draftCount * 10)

  while (drafts.filter((draft) => draft.created).length < draftCount && attempts < maxAttempts) {
    attempts += 1
    const result = await createDraftFromKeyword()
    drafts.push(result)

    if (result?.reason === 'No queued keywords found.') break
  }

  return {
    keywords,
    drafts,
    created: drafts.filter((draft) => draft.created).length,
    skipped: drafts.filter((draft) => draft.skipped).length,
    attempts,
  }
}

async function nextAvailableSlug(baseSlug: string) {
  const supabase = createAdminClient()

  const base =
    cleanKeyword(baseSlug)
      .replace(/\s+/g, '-')
      .replace(/^-+|-+$/g, '') || 'cashclimb-guide'

  for (let i = 0; i < 50; i += 1) {
    const candidate = i === 0 ? base : `${base}-${i + 1}`

    const { data } = await supabase
      .from('posts')
      .select('id')
      .eq('slug', candidate)
      .maybeSingle()

    if (!data) return candidate
  }

  return `${base}-${Date.now()}`
}